-- Schema de referencia (Portfolio OS)
-- Espejo del esquema real usado por la app. Ejecuta en Supabase > SQL Editor
-- si necesitas recrear las tablas en un proyecto nuevo.

-- Tabla de proyectos
create table if not exists public.projects (
  id          bigint generated by default as identity primary key,
  title       text not null,
  description text not null default '',
  repoUrl     text,
  liveUrl     text,
  createdAt   timestamptz not null default now(),
  image       text,
  featured    boolean not null default false
);

alter table public.projects enable row level security;

create policy "Public read projects"
  on public.projects
  for select
  using (true);

-- Tabla de categorias
create table if not exists public.categories (
  id    bigint generated by default as identity primary key,
  slug  text not null unique,
  label text not null
);

alter table public.categories enable row level security;

create policy "Public read categories"
  on public.categories
  for select
  using (true);

-- Tabla puente proyectos <-> categorias
create table if not exists public.project_categories (
  project_id  bigint not null references public.projects (id) on delete cascade,
  category_id bigint not null references public.categories (id) on delete cascade,
  primary key (project_id, category_id)
);

alter table public.project_categories enable row level security;

create policy "Public read project_categories"
  on public.project_categories
  for select
  using (true);

-- Seed: categorias
insert into public.categories (slug, label)
values
  ('personal',   'Proyectos Personales'),
  ('university', 'Proyectos Universidad'),
  ('ux',         'Proyectos UX')
on conflict (slug) do nothing;

-- ─────────────────────────────────────────────
-- Panel admin + Música + Tecnologías + Contenido
-- ─────────────────────────────────────────────

-- Canciones (app de Música)
create table if not exists public.tracks (
  id          bigint generated by default as identity primary key,
  title       text not null,
  url         text not null,
  created_at  timestamptz not null default now()
);
alter table public.tracks enable row level security;
create policy "Public read tracks" on public.tracks for select using (true);
create policy "Admin write tracks" on public.tracks for all to authenticated using (true) with check (true);

-- Tecnologías (tags de proyectos)
create table if not exists public.technologies (
  id    bigint generated by default as identity primary key,
  name  text not null,
  slug  text not null unique,
  logo  text
);
alter table public.technologies enable row level security;
create policy "Public read technologies" on public.technologies for select using (true);
create policy "Admin write technologies" on public.technologies for all to authenticated using (true) with check (true);

-- Puente proyectos <-> tecnologías
create table if not exists public.project_technologies (
  project_id    bigint not null references public.projects (id) on delete cascade,
  technology_id bigint not null references public.technologies (id) on delete cascade,
  primary key (project_id, technology_id)
);
alter table public.project_technologies enable row level security;
create policy "Public read project_technologies" on public.project_technologies for select using (true);
create policy "Admin write project_technologies" on public.project_technologies for all to authenticated using (true) with check (true);

-- Textos editables (chat / portfolio)
create table if not exists public.content_settings (
  key   text primary key,
  value text not null default ''
);
alter table public.content_settings enable row level security;
create policy "Public read content_settings" on public.content_settings for select using (true);
create policy "Admin write content_settings" on public.content_settings for all to authenticated using (true) with check (true);

-- Seed: contenido de About Me (claves about.*) + bio del asistente.
-- Estos valores se pueden sobrescribir desde el panel Admin -> Sobre mí.
insert into public.content_settings (key, value) values
  ('about.name', 'Alexandra Quijada'),
  ('about.role', 'Frontend Developer & UX/UI'),
  ('about.location', 'Venezuela'),
  ('about.email', 'alexandraquijada0207@gmail.com'),
  ('about.linkedin', 'https://www.linkedin.com/in/alexandra-quijada-/'),
  ('about.github', 'https://github.com/alex-quijada'),
  ('about.instagram', 'https://www.instagram.com/alex_quijada_/'),
  ('about.photo', '4.jpeg'),
  ('bio', '## Sobre mí' || E'\n' || '- **Alexandra Quijada**, Frontend Developer & UX/UI' || E'\n' || '- Estudiante de Licenciatura en Informática en la Universidad de Oriente (VE)' || E'\n' || '- Combino diseño de interfaces (UX/UI) con desarrollo web' || E'\n' || '- Ubicación: Venezuela'),
  ('about.perfilBio', 'Desarrolladora frontend con foco en UX/UI. Cuento con experiencia en prácticas profesionales y un portafolio de proyectos personales y universitarios, donde combino diseño de interfaces con desarrollo web.'),
  ('about.education', '[{"title":"Licenciatura en Informática","place":"Universidad de Oriente (VE)","detail":"En curso"}]'),
  ('about.languages', '[{"name":"Español","level":"Nativo"},{"name":"Inglés","level":"A2 · FUNDAUC"}]'),
  ('about.courses', '[{"title":"Aspectos básicos del diseño de la experiencia del usuario","issuer":"Google · Coursera","date":"Sep 2023","url":"https://www.coursera.org/account/accomplishments/verify/V63XBDJL2Z6B"},{"title":"Primeros pasos en el proceso de diseño de UX: Empatizar, definir e idear","issuer":"Google · Coursera","date":"Dic 2023","url":"https://www.coursera.org/account/accomplishments/verify/Z2HRW2BV6ZG6"},{"title":"Crear esquemas de página y prototipos de baja fidelidad","issuer":"Google · Coursera","date":"Abr 2024","url":"https://www.coursera.org/account/accomplishments/verify/HHAACX9CFCNF"},{"title":"Llevar a cabo investigaciones en UX","issuer":"Google · Coursera","date":"May 2025","url":"https://www.coursera.org/account/accomplishments/verify/JMLSFN36AUL1"},{"title":"Crear prototipos y diseños de alta fidelidad en Figma","issuer":"Google · Coursera","date":"Sep 2025","url":"https://www.coursera.org/account/accomplishments/verify/XQEBZLIX4UH5"},{"title":"Crea interfaces de usuario (IU) dinámicas para sitios web","issuer":"Google · Coursera","date":"Dic 2025","url":"https://www.coursera.org/account/accomplishments/verify/UQSJT0BDIQEU"}]')
on conflict (key) do nothing;

-- Seed: tecnologías por defecto (si la tabla está vacía)
insert into public.technologies (name, slug, logo)
select name, slug, null::text from (values
  ('Figma', 'figma'),
  ('TypeScript', 'typescript'),
  ('React', 'react'),
  ('Tailwind CSS', 'tailwind-css'),
  ('Node.js', 'node-js'),
  ('Canvas API', 'canvas-api'),
  ('Framer Motion', 'framer-motion'),
  ('PostgreSQL', 'postgresql')
) as t(name, slug)
where not exists (select 1 from public.technologies);

-- Escritura admin sobre proyectos / categorías
create policy "Admin write projects" on public.projects for all to authenticated using (true) with check (true);
create policy "Admin write categories" on public.categories for all to authenticated using (true) with check (true);
create policy "Admin write project_categories" on public.project_categories for all to authenticated using (true) with check (true);

-- Storage: permitir subir archivos autenticados a los buckets del portfolio
create policy "Auth upload storage"
  on storage.objects
  for insert
  to authenticated
  with check (bucket_id in ('project-images', 'music', 'YO'));

-- ─────────────────────────────────────────────
-- Pasos manuales en el dashboard:
-- 1) Authentication → Users → Add user → alexandraquijada@gmail.com / Lusandre02.07
--    (contraseña la misma que se pide en el panel Admin de la app; activa "Auto Confirm User")
-- 2) Ejecutar este script completo en SQL Editor
-- Nota: la app de Música usa URLs de YouTube (tabla tracks), ya no sube MP3 a storage.
-- ─────────────────────────────────────────────